services:
  postgres:
    image: postgres:16
    container_name: sbexercise-postgres
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/load-data.sql:/docker-entrypoint-initdb.d/02-load-data.sql
      - ./data:/data
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d products"]
      interval: 5s
      timeout: 5s
      retries: 10

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: sbexercise-app
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/product
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#    ports:
#      - "8080:8080"

volumes:
  postgres_data: